"""The de-identified matrix a public host runs on.

The supplied case package is confidential and does not leave the machine that
holds it, so a deployed instance is served the pseudonymised item score matrix
instead. The claim that makes that acceptable is a strong one, and it has two
halves that fail in different ways:

    the export carries no supplied identifier
    the engine computes the SAME answers from it

The real export can never be committed, and CI has neither it nor the workbooks,
so these tests build a synthetic matrix and exercise the code paths against it.
The real artifact is checked by scripts/check_deidentified.py and by the parity
proof inside scripts/export_deidentified.py, both of which run where both halves
are in hand. Neither half is sufficient alone and this file is the one that runs
everywhere.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from caliper.ingest.normalize import DEIDENTIFIED_EXPORT, Observation, load_all, load_deidentified
from caliper.instrument.audit import audit_all


def synthetic_observations() -> list[Observation]:
    """A small design with enough structure for the audit to have an opinion.

    Four raters, eight agents, six items. The pass pattern is a fixed bit mask
    per evaluation rather than a formula over the indices: an earlier version
    used (occasion + item) % 3, which gives every evaluation the SAME total
    score, and a total with zero variance makes KR-20 undefined. The engine was
    right to refuse it. A fixture has to exercise the thing, not merely populate
    it.
    """
    # One byte per evaluation, six bits used. Chosen so total scores differ.
    masks = [0b000111, 0b101101, 0b110010, 0b011011, 0b111110, 0b000001, 0b101011, 0b010101]
    rows: list[Observation] = []
    for occasion, mask in enumerate(masks):
        agent = f"A-{occasion:04x}"
        rater = f"R-{occasion % 4:04x}"
        for item in range(6):
            rows.append(
                Observation(
                    eval_id=f"E-{occasion:04x}",
                    agent_ref=agent,
                    rater_ref=rater,
                    domain="member_experience",
                    item_id=f"ME-{item}",
                    item_text=f"synthetic item {item}",
                    passed=bool(mask & (1 << item)),
                    call_date="2026-01-01",
                    occasion_index=occasion,
                )
            )
    return rows


def write_export(directory: Path, rows: list[Observation], **extra) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / DEIDENTIFIED_EXPORT
    payload = {
        "schema": 1,
        "note": "synthetic, generated by the test suite",
        "redactions": {"DATE_OF_SERVICE": 3},
        "observations": [o.as_dict() for o in rows],
        **extra,
    }
    path.write_text(json.dumps(payload, indent=1, sort_keys=True))
    return path


def test_the_export_never_contains_a_date(tmp_path: Path) -> None:
    """Observation drops the date at its serialization boundary.

    That is the mechanism the whole export relies on, so it is asserted on the
    written bytes rather than on the object: a future field added to Observation
    would ride out through as_dict without anyone noticing.
    """
    path = write_export(tmp_path, synthetic_observations())
    raw = path.read_text()
    assert "call_date" not in raw
    assert "2026-01-01" not in raw


def test_load_all_prefers_the_export_when_it_is_present(tmp_path: Path) -> None:
    """A directory holding the export is served from it.

    There are no workbooks in tmp_path at all, so the raw path would raise
    FileNotFoundError. Reaching the rows proves the branch was taken rather than
    merely available.
    """
    write_export(tmp_path, synthetic_observations())
    observations, redactions, salt = load_all(tmp_path)

    assert len(observations) == 48
    assert redactions == {"DATE_OF_SERVICE": 3}
    # Nothing is left to pseudonymise, and the salt that made these references
    # was used once and never recorded.
    assert salt == ""
    assert all(o.call_date == "" for o in observations)


def test_the_audit_is_identical_across_the_round_trip(tmp_path: Path) -> None:
    """The load bearing claim: the host computes what this machine computes.

    If this can drift, the deployed instance is a demonstration rather than the
    product, and the difference would be invisible: both sides render a number
    with the same label.
    """
    rows = synthetic_observations()
    path = write_export(tmp_path, rows)
    round_tripped, _ = load_deidentified(path)

    before = audit_all(rows, {})
    after = audit_all(round_tripped, {})

    for domain, a in before["domains"].items():
        b = after["domains"][domain]
        for key in ("point_estimate", "ci_low", "ci_high", "n_evaluations", "n_items"):
            assert a["reliability"][key] == pytest.approx(b["reliability"][key], abs=1e-12), (
                f"{domain}.{key} drifted across the export"
            )
        assert [i["item_id"] for i in a["items"]] == [i["item_id"] for i in b["items"]]
        for i, j in zip(a["items"], b["items"], strict=True):
            assert sorted(i["flags"]) == sorted(j["flags"])
    assert before["connectivity"] == after["connectivity"]


def test_a_truncated_export_cannot_pass_as_the_real_one(tmp_path: Path) -> None:
    """Guards the guard.

    The volume floors in scripts/check_deidentified.py only matter if a short
    export would actually be wrong. It is, in two different ways depending on how
    short: a badly truncated matrix makes the coefficient undefined and the
    engine refuses it, and a mildly truncated one silently answers a different
    question. Both are caught here, and the floor is what stops either reaching a
    host.
    """
    rows = synthetic_observations()
    full = audit_all(rows, {})["domains"]["member_experience"]["reliability"]["point_estimate"]

    # Badly truncated: too few evaluations for the statistic to exist at all.
    with pytest.raises(ValueError):
        audit_all(rows[: len(rows) // 8], {})

    # Mildly truncated: it computes, and it is a different number. This is the
    # dangerous case, because nothing errors and the page renders.
    fewer = [o for o in rows if o.occasion_index < 6]
    partial = audit_all(fewer, {})["domains"]["member_experience"]["reliability"]["point_estimate"]
    assert partial != full, "dropping two evaluations must not leave the coefficient unchanged"


def test_an_empty_export_refuses_rather_than_returning_nothing(tmp_path: Path) -> None:
    """An empty matrix must not read as a successful load of zero observations.

    Downstream, an empty list produces an audit with no items, which renders as a
    page with no findings rather than as an error.
    """
    path = write_export(tmp_path, [])
    with pytest.raises(ValueError, match="no observations"):
        load_deidentified(path)
