"""Prove the de-identified export carries no identifier, before it ships.

The export in data/deidentified is the only piece of the supplied case package
that reaches a public host. It is generated by a script, and a generator is
exactly the kind of thing that keeps working after its assumptions stop being
true: one added column, one changed serialization boundary, and confidential
material rides out with it while every test stays green.

So this does not trust the generator. It reads the shipped file and asserts
against its bytes.

The checks are two sided on purpose, because a scan that walked nothing reports
clean in the same words as a scan that walked everything:

    want 0   no identifier pattern anywhere in the file
    want 0   no field outside the agreed set
    want 0   no salt, so the pseudonyms cannot be reversed
    want N   a floor on observations, evaluations, agents and raters, so an
             empty or truncated export cannot pass

Run: python scripts/check_deidentified.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from caliper.ingest.pii_scan import PATTERNS  # noqa: E402

EXPORT = ROOT / "data" / "deidentified" / "observations.json"

# Exactly the fields the engine reads. Anything else is a leak by definition,
# whether or not a pattern happens to match it.
ALLOWED_FIELDS = {
    "eval_id",
    "agent_ref",
    "rater_ref",
    "domain",
    "item_id",
    "item_text",
    "passed",
    "occasion_index",
}

# From the verified evidence spine. These are floors, not equalities, so the
# export can grow; what they forbid is an empty or truncated file passing.
MIN_OBSERVATIONS = 300
MIN_EVALUATIONS = 15
MIN_AGENTS = 8
MIN_RATERS = 2

# A salt would make every pseudonym reversible by anyone holding the original
# workbook, since the identifier space is tiny.
FORBIDDEN_KEYS = {"salt", "pseudonym_salt", "caliper_pseudonym_salt", "key", "secret"}


def main() -> int:
    if not EXPORT.exists():
        print(f"FAIL  no export at {EXPORT.relative_to(ROOT)}")
        print("      run: python scripts/export_deidentified.py")
        return 1

    raw = EXPORT.read_text()
    payload = json.loads(raw)
    rows = payload.get("observations", [])

    failures = 0

    def check(name: str, ok: bool, detail: str = "") -> None:
        nonlocal failures
        print(f"  {'ok  ' if ok else 'FAIL'}  {name}{('  ' + detail) if detail else ''}")
        if not ok:
            failures += 1

    # 1. Volume floors. Run first, so everything after is known to be scanning
    #    real content rather than an empty list.
    check("observations present", len(rows) >= MIN_OBSERVATIONS, f"{len(rows)} (floor {MIN_OBSERVATIONS})")
    if len(rows) < MIN_OBSERVATIONS:
        return 1

    evals = {r.get("eval_id") for r in rows}
    agents = {r.get("agent_ref") for r in rows}
    raters = {r.get("rater_ref") for r in rows}
    check("evaluations present", len(evals) >= MIN_EVALUATIONS, f"{len(evals)}")
    check("agents present", len(agents) >= MIN_AGENTS, f"{len(agents)}")
    check("raters present", len(raters) >= MIN_RATERS, f"{len(raters)}")

    # 2. Field allowlist. A new column added upstream fails here rather than
    #    riding out because no regex happened to match it.
    seen: set[str] = set()
    for r in rows:
        seen.update(r.keys())
    extra = seen - ALLOWED_FIELDS
    check("no field outside the agreed set", not extra, f"unexpected: {sorted(extra)}" if extra else "")

    # 3. Identifier patterns, across the WHOLE file rather than per field, so a
    #    value that moves to a different key is still caught.
    hits: dict[str, int] = {}
    for kind, pattern in PATTERNS:
        n = len(pattern.findall(raw))
        if n:
            hits[kind] = n
    check("no identifier pattern anywhere in the file", not hits, str(hits) if hits else "")

    # 4. Pseudonyms must not be reversible.
    lowered = {k.lower() for k in payload}
    leaked = lowered & FORBIDDEN_KEYS
    check("no salt in the export", not leaked, str(sorted(leaked)) if leaked else "")

    # 5. The pseudonyms must actually look pseudonymous rather than passed
    #    through. A real name would not match this shape.
    shaped = [r for r in rows if isinstance(r.get("agent_ref"), str) and r["agent_ref"].count("-") == 1]
    check("agent references are pseudonyms", len(shaped) == len(rows), f"{len(shaped)} of {len(rows)}")

    # 6. The scores have to be scores.
    values = {r.get("passed") for r in rows}
    check("passed is boolean or null", values <= {True, False, None}, str(sorted(map(str, values))))

    if failures:
        print(f"\n{failures} check(s) failed; this export must not be shipped")
    else:
        print(f"\nclean: {len(rows)} observations carry no supplied identifier")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
