"""Drive the whole judge path in a real browser against the DEPLOYED origin.

A green unit suite tests the code. It has never once proven that the thing a
judge opens actually works, and this project has already shipped two defects
that were invisible to every test and every build: a production bundle pointing
at localhost, and a WebSocket that failed by going silent. Both were found only
by opening the page.

So this walks the path a judge walks, on the origin a judge opens, and asserts
the state actually changed rather than that a click returned.

Local gate, deliberately not in CI: CI has no browsers, and a suite that skips
there would be a false green of exactly the kind the rest of this repo refuses.

    .venv/bin/python scripts/e2e_judge_path.py
    .venv/bin/python scripts/e2e_judge_path.py --base http://127.0.0.1:8000
"""

from __future__ import annotations

import argparse
import re
import sys

DEPLOYED = "https://caliper-77ma.onrender.com"
# The free host cold starts, so a first paint can genuinely take half a minute.
# A short timeout here would report a sleeping host as a broken product.
NAV_TIMEOUT_MS = 90_000
ACT_TIMEOUT_MS = 45_000

# Regenerated by the engine, asserted here so a silently wrong deploy is caught.
EXPECTED_BANDS = {
    "Business Process": "2 of 4",
    "Compliance": "10 of 10",
    "Member Experience": "5 of 9",
}


class Failed(Exception):
    pass


def check(condition: bool, message: str) -> None:
    if not condition:
        raise Failed(message)


def run(base: str, phone: bool) -> list[str]:
    from playwright.sync_api import sync_playwright

    notes: list[str] = []
    with sync_playwright() as p:
        browser = p.chromium.launch()
        context = browser.new_context(
            **(p.devices["iPhone 14"] if phone else {}),
        )
        page = context.new_page()
        console_errors: list[str] = []
        page.on(
            "console",
            lambda m: console_errors.append(m.text) if m.type == "error" else None,
        )
        failed_requests: list[str] = []
        page.on(
            "response",
            lambda r: (
                failed_requests.append(f"{r.status} {r.url}")
                if r.status >= 400 and "/api/" in r.url
                else None
            ),
        )
        page.set_default_timeout(ACT_TIMEOUT_MS)
        page.set_default_navigation_timeout(NAV_TIMEOUT_MS)

        page.goto(base, wait_until="domcontentloaded")
        check("CALIPER" in page.title(), f"unexpected title: {page.title()!r}")
        notes.append("screen 01 loaded")

        page.get_by_role("button", name="Run the audit").click()
        # The run id is the thread through the whole demo. If it never appears,
        # the engine did not run, whatever the page looks like.
        page.wait_for_selector("text=/RUN-[0-9A-F]{8}/", timeout=ACT_TIMEOUT_MS)
        body = page.inner_text("body")
        run_id = re.search(r"RUN-[0-9A-F]{8}", body)
        check(run_id is not None, "no run id appeared after Run the audit")
        notes.append(f"audit ran, {run_id.group(0)}")

        check("AWAITING_APPROVAL" in body, "run did not reach AWAITING_APPROVAL")
        notes.append("gate is holding the run")

        for form, band in EXPECTED_BANDS.items():
            check(
                re.search(rf"{re.escape(form)}\s*{re.escape(band)}", body) is not None,
                f"{form} did not show {band}; the deployed engine disagrees with ours",
            )
        notes.append("all three forms show the computed bands")

        # The four actions must be refused until a person is named. This is the
        # product's central claim, so assert the refusal, not just the buttons.
        approve = page.get_by_role("button", name=re.compile("^Approve"))
        check(approve.is_disabled(), "Approve was enabled with nobody named")
        notes.append("gate refuses an unnamed decider")

        page.get_by_role("textbox", name="who is deciding").fill("e2e gate check")
        check(approve.is_enabled(), "Approve stayed disabled after naming a decider")
        approve.click()

        page.wait_for_selector("text=INTERVENTION_GENERATED", timeout=ACT_TIMEOUT_MS)
        notes.append("approval advanced the run state")

        after = page.inner_text("body")
        check("Download the design workbook" in after, "workbook link never appeared")
        href = page.get_by_role("link", name=re.compile("Download the design workbook"))
        target = href.get_attribute("href") or ""
        check("/workbook" in target, f"workbook link points at {target!r}")
        notes.append("workbook link is wired to the run")

        check(not console_errors, f"console errors: {console_errors[:3]}")
        check(not failed_requests, f"failing API calls: {failed_requests[:3]}")
        notes.append("no console errors, no failing API calls")

        if phone:
            overflow = page.evaluate(
                "() => document.documentElement.scrollWidth > document.documentElement.clientWidth"
            )
            check(not overflow, "page scrolls horizontally at phone width")
            small = page.evaluate(
                "() => [...document.querySelectorAll('input,select,textarea')]"
                ".filter(e => parseFloat(getComputedStyle(e).fontSize) < 16).length"
            )
            check(small == 0, f"{small} field(s) under 16px will zoom iOS permanently")
            notes.append("no horizontal overflow, no iOS zoom trap")

        browser.close()
    return notes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default=DEPLOYED)
    args = parser.parse_args()

    try:
        import playwright  # noqa: F401
    except ImportError:
        print(
            "playwright is not installed in this environment.\n"
            "  .venv/bin/python -m pip install playwright\n"
            "  .venv/bin/python -m playwright install chromium\n"
            "This is a local gate and is deliberately not a project dependency.",
            file=sys.stderr,
        )
        return 2

    failures = 0
    for phone in (False, True):
        label = "phone  " if phone else "desktop"
        try:
            for note in run(args.base, phone):
                print(f"  {label}  ok    {note}")
        except Failed as error:
            print(f"  {label}  FAIL  {error}", file=sys.stderr)
            failures += 1
        except Exception as error:  # noqa: BLE001
            # A harness that breaks must not read as a product that works.
            print(f"  {label}  ERROR {type(error).__name__}: {error}", file=sys.stderr)
            failures += 1

    print()
    if failures:
        print(f"{failures} viewport(s) failed against {args.base}", file=sys.stderr)
        return 1
    print(f"judge path works end to end on {args.base}, desktop and phone")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
