"""Render docs/sequence.md into a standalone viewer at docs/sequence.html.

The diagram is extracted from the committed markdown rather than duplicated,
because two copies of a diagram is two diagrams, and the second one goes stale
the first time somebody edits an arrow. Run this after changing sequence.md.

    .venv/bin/python scripts/render_sequence.py
    .venv/bin/python scripts/render_sequence.py --check   # CI style, no write
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "sequence.md"
TARGET = ROOT / "docs" / "sequence.html"

TEMPLATE = """<!doctype html>
<meta charset="utf-8">
<title>CALIPER: one run, end to end</title>
<!-- Generated by scripts/render_sequence.py from docs/sequence.md. Do not edit
     by hand: the diagram lives in the markdown and this file is a view of it. -->
<style>
  body {{ margin:0; background:#0d1117; color:#e6edf3;
         font:14px/1.5 -apple-system,"Helvetica Neue",Arial,sans-serif; }}
  header {{ padding:18px 24px 6px; border-bottom:1px solid #21262d; }}
  h1 {{ margin:0 0 4px; font-size:19px; letter-spacing:-.3px; }}
  p  {{ margin:0; color:#8b949e; font-size:13px; }}
  .wrap {{ padding:18px 12px 60px; overflow:auto; }}
  .mermaid {{ transform-origin: top left; }}
  .bar {{ position:fixed; bottom:0; left:0; right:0; background:#161b22;
         border-top:1px solid #21262d; padding:9px 16px; display:flex;
         gap:10px; align-items:center; font-size:13px; }}
  button {{ background:#21262d; color:#e6edf3; border:1px solid #30363d;
           border-radius:6px; padding:5px 12px; font-size:13px; cursor:pointer; }}
  button:hover {{ background:#30363d; }}
  #z {{ color:#8b949e; min-width:52px; }}
</style>
<header>
  <h1>CALIPER: one run, end to end</h1>
  <p>Read off the shipped api client, routes and state machine. Every endpoint and state verified to exist.</p>
</header>
<div class="wrap"><pre class="mermaid">
{diagram}
</pre></div>
<div class="bar">
  <button onclick="zoom(-0.15)">zoom out</button>
  <button onclick="zoom(0.15)">zoom in</button>
  <button onclick="setZ(1)">reset</button>
  <span id="z">100%</span>
  <span style="color:#8b949e">one model call, and it sits after the human approval</span>
</div>
<script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
<script>
  mermaid.initialize({{ startOnLoad:true, theme:'dark',
                       sequence:{{ useMaxWidth:false, wrap:true, width:170 }} }});
  var s = 1;
  function setZ(v){{ s = Math.min(3, Math.max(0.3, v));
    document.querySelector('.mermaid').style.transform = 'scale('+s+')';
    document.getElementById('z').textContent = Math.round(s*100)+'%'; }}
  function zoom(d){{ setZ(s+d); }}
</script>
"""


def build() -> str:
    text = SOURCE.read_text()
    match = re.search(r"```mermaid\n(.*?)```", text, re.S)
    if match is None:
        raise SystemExit(f"no mermaid block in {SOURCE}")
    diagram = match.group(1).strip()
    # Floor it. A regex that silently matched an empty block would render a
    # blank page that looks like a styling problem rather than a missing source.
    if len(diagram.splitlines()) < 10:
        raise SystemExit(f"the mermaid block is only {len(diagram.splitlines())} lines, refusing")
    return TEMPLATE.format(diagram=diagram)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the rendered file is stale")
    args = parser.parse_args()

    html = build()
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != html:
            print(
                f"{TARGET.relative_to(ROOT)} is stale. "
                "Run: .venv/bin/python scripts/render_sequence.py",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.relative_to(ROOT)} matches {SOURCE.relative_to(ROOT)}")
        return 0

    TARGET.write_text(html)
    print(f"wrote {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
